### ISSUE TITLE
Even after installing tk, module error occurs...

### ISSUE THREAD

**Issue by SR-Hossain** [Rijwanul-Haque-Roman/YouTube_Downloader#1]
```bash
$ python main.py                                                                                                               ✔ 
Traceback (most recent call last):
  File "/home/sr/YouTube_Downloader/main.py", line 1, in <module>
    import tkinter as tk
  File "/usr/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```

**Comment by Rijwanul-Haque-Roman** [comment]
Will look into it.

**Comment by rizwanul-haque-roman** [comment]
> ```shell
> $ python main.py                                                                                                               ✔ 
> Traceback (most recent call last):
>   File "/home/sr/YouTube_Downloader/main.py", line 1, in <module>
>     import tkinter as tk
>   File "/usr/lib/python3.11/tkinter/__init__.py", line 38, in <module>
>     import _tkinter # If this fails your Python may not be configured for Tk
>     ^^^^^^^^^^^^^^^
> ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
> ```

**To fix this issue, you can try the following steps:**

+ Install the required Tkinter package and dependencies:\
Depending on your Linux distribution, you can use the package manager to install the necessary packages. For example, if you're using Ubuntu or Debian-based systems, you can use apt:
```
sudo apt update
sudo apt install python3-tk
```
If you're using a different Linux distribution, use the appropriate package manager and package name to install tkinter.

+ If you have recently installed the required package, try restarting your terminal or the Python environment to update the system's library paths.

+ If the issue persists, it's possible that the library path is not set correctly. You can set the library path manually by exporting it before running your Python script. Open a terminal and run:
```
export LD_LIBRARY_PATH=/path/to/tk/libraries:$LD_LIBRARY_PATH
```
Replace **'/path/to/tk/libraries'** with the directory where the **'libtk8.6.so'** library is located. This step might be necessary if the library is installed in a non-standard location.

+ If you are using a virtual environment, make sure that it is properly configured and has access to the required system libraries.

+ Double-check that you are using the correct Python interpreter. Sometimes, there might be multiple Python installations on your system, and the error might occur if the wrong interpreter is being used.

+ If none of the above steps work, try reinstalling the tkinter package:
```
pip install --upgrade --force-reinstall tkinter
```
This command will reinstall the tkinter package and might fix any potential issues.

After trying these steps, attempt to run your main.py script again:
```
python main.py
```
If the problem persists, please double-check the Tkinter installation and ensure that the required **'libtk8.6.so'** file is present in the system library paths. If you have a non-standard system configuration or using a different OS, the steps may vary, and you might need to seek specific help for your setup.
